-- Fix password for all users (password: 123456)
-- BCrypt hash generated by Spring Security BCryptPasswordEncoder
SET search_path TO core_service;
UPDATE users SET password_hash = '$2a$10$2KHDiHhzNBsmBrbcmbJw/.zL7j0nsYOJ6FeyLKzgcUo/EZoLG29qi' WHERE email LIKE '%@smd.edu.vn';
