import { SyllabusDetail, SyllabusListItem } from '../types';

export const mockSyllabi: SyllabusListItem[] = [
  {
    id: '1',
    code: 'CS301',
    nameVi: 'Cơ sở dữ liệu',
    nameEn: 'Database Systems',
    term: 'HK2 2024-2025',
    credits: 3,
    faculty: 'Khoa Công nghệ Thông tin',
    program: 'Khoa học Máy tính',
    lecturerName: 'TS. Lê Văn C',
    lecturerEmail: 'levanc@university.edu',
    status: 'PUBLISHED',
    tracked: true,
    progress: 100,
    majorShort: 'CS',
    publishedAt: '2024-12-01',
  },
  {
    id: '2',
    code: 'CS401',
    nameVi: 'Trí tuệ nhân tạo',
    nameEn: 'Artificial Intelligence',
    term: 'HK2 2024-2025',
    credits: 3,
    faculty: 'Khoa Công nghệ Thông tin',
    program: 'Khoa học Máy tính',
    lecturerName: 'PGS. Phạm Thị D',
    lecturerEmail: 'phamthid@university.edu',
    status: 'PUBLISHED',
    tracked: false,
    progress: 100,
    majorShort: 'CS',
    publishedAt: '2024-12-03',
  },
  {
    id: '3',
    code: 'CS201',
    nameVi: 'Cấu trúc dữ liệu',
    nameEn: 'Data Structures',
    term: 'HK1 2024-2025',
    credits: 3,
    faculty: 'Khoa Công nghệ Thông tin',
    program: 'Khoa học Máy tính',
    lecturerName: 'PGS. Trần Thị B',
    lecturerEmail: 'tranthib@university.edu',
    status: 'PUBLISHED',
    tracked: true,
    progress: 100,
    majorShort: 'CS',
    publishedAt: '2024-10-20',
  },
  {
    id: '4',
    code: 'EE201',
    nameVi: 'Mạch điện tử',
    nameEn: 'Electronic Circuits',
    term: 'HK1 2024-2025',
    credits: 3,
    faculty: 'Khoa Điện - Điện tử',
    program: 'Kỹ thuật Điện tử',
    lecturerName: 'TS. Hoàng Văn E',
    lecturerEmail: 'hoangvane@university.edu',
    status: 'PUBLISHED',
    tracked: false,
    progress: 100,
    majorShort: 'EE',
    publishedAt: '2024-09-25',
  },
  {
    id: '5',
    code: 'CS101',
    nameVi: 'Lập trình căn bản',
    nameEn: 'Introduction to Programming',
    term: 'HK1 2024-2025',
    credits: 3,
    faculty: 'Khoa Công nghệ Thông tin',
    program: 'Khoa học Máy tính',
    lecturerName: 'TS. Nguyễn Văn A',
    lecturerEmail: 'nguyenvana@university.edu',
    status: 'PUBLISHED',
    tracked: false,
    progress: 100,
    majorShort: 'CS',
    publishedAt: '2024-09-01',
  },
];

const commonDetail = (base: SyllabusListItem): SyllabusDetail => ({
  ...base,
  summaryInline:
    'Đây là môn học nền tảng, tập trung vào kiến trúc nội dung và đánh giá. Nội dung mang tính tham khảo.',
  description:
    'Môn học cung cấp kiến thức nền tảng về nội dung học phần, cấu trúc đề cương và phương pháp tổ chức học tập.',
  objectives: [
    'Hiểu khái niệm và cấu trúc tài liệu học phần',
    'Thiết kế được mục tiêu và chuẩn đầu ra (CLO)',
    'Đọc hiểu ma trận đánh giá và trọng số',
    'Áp dụng vào việc tự học và làm bài tập',
  ],
  teachingMethods: 'Giảng lý thuyết kết hợp thực hành, làm việc nhóm trên bài tập và tình huống.',
  studentTasks: [
    'Tham gia đầy đủ các buổi học (tối thiểu 80% số tiết)',
    'Hoàn thành bài tập/quiz theo yêu cầu',
    'Tham gia thảo luận và hoạt động nhóm',
    'Tự nghiên cứu tài liệu trước và sau buổi học',
  ],
  timeAllocation: { theory: 30, practice: 30, selfStudy: 90 },
  prerequisite: { text: 'Xem cây quan hệ' },
  assessmentMatrix: [
    { method: 'Thi giữa kỳ', form: 'Thi', clo: ['CLO1', 'CLO2'], criteria: 'A1.2', weight: 30 },
    {
      method: 'Thi cuối kỳ',
      form: 'Thi',
      clo: ['CLO1', 'CLO2', 'CLO3', 'CLO4'],
      criteria: 'A2.1',
      weight: 40,
    },
    { method: 'Dự án nhóm', form: 'Nhóm', clo: ['CLO3', 'CLO4'], criteria: 'A3.1', weight: 20 },
    {
      method: 'Bài tập thực hành',
      form: 'Cá nhân',
      clo: ['CLO2', 'CLO3'],
      criteria: 'A1.1',
      weight: 10,
    },
  ],
  clos: [
    {
      code: 'CLO1',
      description: 'Hiểu và giải thích các khái niệm cơ bản',
      bloomLevel: 'Hiểu',
      weight: 20,
      plo: ['PLO1', 'PLO2'],
    },
    {
      code: 'CLO2',
      description: 'Thiết kế mô hình và chuẩn hóa',
      bloomLevel: 'Áp dụng',
      weight: 25,
      plo: ['PLO2', 'PLO4'],
    },
    {
      code: 'CLO3',
      description: 'Viết truy vấn/phân tích vấn đề',
      bloomLevel: 'Áp dụng',
      weight: 30,
      plo: ['PLO2', 'PLO3'],
    },
    {
      code: 'CLO4',
      description: 'Phân tích và tối ưu',
      bloomLevel: 'Phân tích',
      weight: 25,
      plo: ['PLO4', 'PLO5'],
    },
  ],
  ploList: ['PLO1', 'PLO2', 'PLO3', 'PLO4', 'PLO5'],
  cloPloMap: {
    CLO1: ['PLO1', 'PLO2'],
    CLO2: ['PLO2', 'PLO4'],
    CLO3: ['PLO2', 'PLO3'],
    CLO4: ['PLO4', 'PLO5'],
  },
  textbooks: [
    'Database System Concepts - Silberschatz (7th Edition)',
    'SQL Queries for Mere Mortals - Viescas',
  ],
  references: ['Fundamentals of Database Systems - Elmasri & Navathe', 'MySQL Documentation'],
});

export const mockDetailsById: Record<string, SyllabusDetail> = Object.fromEntries(
  mockSyllabi.map((s) => [s.id, commonDetail(s)])
);
